<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <OutputType Condition="'$(Configuration)' == 'Debug'">Exe</OutputType>
    <DisableWinExeOutputInference>true</DisableWinExeOutputInference>
    <InformationalVersion Condition="'$(EdifierVersion)' != ''">$(EdifierVersion)</InformationalVersion>
    <InformationalVersion Condition="'$(EdifierVersion)' == ''">dev-build</InformationalVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <FfiProfile Condition="'$(Configuration)' == 'Release'">release</FfiProfile>
    <FfiProfile Condition="'$(Configuration)' != 'Release'">debug</FfiProfile>
    <ApplicationIcon Condition="Exists('..\..\target\windows\assets\AppIcon.ico')">..\..\target\windows\assets\AppIcon.ico</ApplicationIcon>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <RootNamespace>EdifierCtrl</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>x64;ARM64</Platforms>
    <RuntimeIdentifiers>win-x64;win-arm64</RuntimeIdentifiers>
    <RollForward>LatestMajor</RollForward>
    <UseWinUI>true</UseWinUI>
    <WindowsPackageType>None</WindowsPackageType>
    <WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
    <WindowsAppSdkBootstrapInitialize>false</WindowsAppSdkBootstrapInitialize>
    <EnableMsixTooling>true</EnableMsixTooling>
    <EnableCoreMrtTooling>true</EnableCoreMrtTooling>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.6.250108002" GeneratePathProperty="true" />
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.26100.1742" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="..\..\target\$(FfiProfile)\edifier_ffi.dll" Link="edifier_ffi.dll" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="..\..\target\windows\assets\AppIcon.ico" Link="Assets\AppIcon.ico" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" Condition="Exists('..\..\target\windows\assets\AppIcon.ico')" />
  </ItemGroup>
</Project>
