[package]
name = "edifier-bt-linux"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Linux BlueZ 蓝牙适配"

[dependencies]
edifier-protocol = { workspace = true }
edifier-runtime = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
bluer = { version = "0.17", features = ["bluetoothd", "rfcomm"] }
dbus = { version = "0.9", features = ["futures"] }
dbus-tokio = "0.7"
