[package]
name = "edifier-bt-macos"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "macOS IOBluetooth 适配"

[dependencies]
edifier-runtime = { workspace = true }
edifier-protocol = { workspace = true }
async-trait = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[target.'cfg(target_os = "macos")'.dependencies]
libc = "0.2"
